language: node_js
node_js:
  - 'stable'

services:
  - docker

script:
  - gulp test
  - gulp

after_success:
  - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD} ${DOCKER_SERVER}
  - DOCKER_IMAGE=${DOCKER_REPO}/everempire-webapp:latest
  - docker build -t ${DOCKER_IMAGE} .
  - docker push ${DOCKER_IMAGE}
  - DOCKER_IMAGE_TAG=${DOCKER_REPO}/everempire-webapp:${TRAVIS_COMMIT}
  - docker tag ${DOCKER_IMAGE} ${DOCKER_IMAGE_TAG}
  - docker push ${DOCKER_IMAGE_TAG}
